[package]
name = "AetherInstaller"
version = "0.1.0"
edition = "2024"

[dependencies]
dark-light = "0.2"
dirs = "6.0"
eframe = "0.27"
egui = "0.27"
image = "0.25"
reqwest = { version = "0.12", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10"
sys-locale = "0.3"
zip = "8.6"
